services:
  frontend:
    build: .
    image: asistencias-frontend:latest
    container_name: frontend_asistencias
    ports:
      - "4200:80"
    environment:
      API_URL: ${API_URL:-http://localhost:8080/api/v1}
      KEYCLOAK_URL: ${KEYCLOAK_URL:-http://127.0.0.1:8081}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-asistencias-uco}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-asistencias-uco-frontend}
      USE_MOCKS: ${USE_MOCKS:-false}
